/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_doom_host                      19
#define gattdb_clientTics1                    21
#define gattdb_clientTics2                    24
#define gattdb_clientTics3                    27
#define gattdb_doom_client                    29
#define gattdb_doom_client_cmd                31
#define gattdb_otherNodeTics                  34


#endif // __GATT_DB_H
